services:
    postgres:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    mailhog:
        image: mailhog/mailhog
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"

volumes:
    postgres:
